[package]
version = "0.1.0"
name = "sm2-script"
edition = "2021"
default-run = "sm2"

[[bin]]
name = "sm2"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
rand = "0.8"
sm2 = { version = "0.14.0-rc.4", features = ["dsa", "arithmetic", "serde"] }
sp1-sdk = "5.0.8"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
alloy-sol-types = { workspace = true }
shared-lib = { path = "../lib" }
dotenv = "0.15.0"


[build-dependencies]
sp1-build = "5.0.8"
